config/routes.rb
CadastroDeFilmes::Application.routes.draw do
  resources :filmes

  resources :roteiristas

  resources :atores

  resources :midias

  resources :paises

  resources :generos

  resources :diretores

  root :to => 'filmes#index'

end

app/models/midia.rb
class Midia < ActiveRecord::Base
  has_many :filmes

  validates :nome, uniqueness: true, presence: true
end

app/controllers/midias_controller.rb
#encoding: utf-8
class MidiasController < ApplicationController
  before_action :set_midia, only: [:show, :edit, :update, :destroy]
  # GET /midias
  # GET /midias.json
  def index
    @midias = Midia.all
  end

  # GET /midias/1
  # GET /midias/1.json
  def show
    @midia = Midia.find(params[:id])
  end

  # GET /midias/new
  # GET /midias/new.json
  def new
    @midia = Midia.new
  end

  # GET /midias/1/edit
  def edit
    @midia = Midia.find(params[:id])
  end

  # POST /midias
  # POST /midias.json
  def create
    @midia = Midia.new(midia_params)

    respond_to do |format|
      if @midia.save
        format.html { redirect_to @midia, notice: 'Um novo tipo de mídia foi criado com sucesso.' }
        format.json { render json: @midia, status: :created, location: @midia }
      else
        format.html { render action: "new" }
        format.json { render json: @midia.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /midias/1
  # PUT /midias/1.json
  def update
    respond_to do |format|
      if @midia.update_attributes(midia_params)
        format.html { redirect_to @midia, notice: 'O tipo de mídia foi atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @midia.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /midias/1
  # DELETE /midias/1.json
  def destroy
    @midia.destroy

    respond_to do |format|
      format.html { redirect_to midias_url }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_midia
      @midia = Midia.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def midia_params
      params.require(:midia).permit(:nome)
    end
end

app/helpers/midias_helper.rb
module MidiasHelper
end

app/views/midias/_form.html.erb
<%= form_for(@midia) do |f| %>
  <% if @midia.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@midia.errors.count, "error") %> Não foi possível salvar essa mídia:</h2>

      <ul>
      <% @midia.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/midias/edit.html.erb
<h1>Editando tipos de mídia</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @midia %> |
<%= link_to 'Voltar', midias_path %>

app/views/midias/index.html.erb
<h1>Listando mídias</h1>

<table>
  <tr>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @midias.each do |midia| %>
  <tr>
    <td><%= midia.nome %></td>
    <td><%= link_to 'Mostrar', midia %></td>
    <td><%= link_to 'Editar', edit_midia_path(midia) %></td>
    <td><%= link_to 'Apagar', midia, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Criar novo Midia', new_midia_path %>

app/views/midias/new.html.erb
<h1>Criar novo tipo de mídia</h1>

<%= render 'form' %>

<%= link_to 'Voltar', midias_path %>

app/views/midias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @midia.nome %>
</p>


<%= link_to 'Editar', edit_midia_path(@midia) %> |
<%= link_to 'Voltar', midias_path %>