config/routes.rb
CadastroDeFilmes::Application.routes.draw do
  resources :filmes

  resources :roteiristas

  resources :atores

  resources :midias

  resources :paises

  resources :generos

  resources :diretores

  root :to => 'filmes#index'

end

app/controllers/paises_controller.rb
#encoding: utf-8
class PaisesController < ApplicationController
  before_action :set_pais, only: [:show, :edit, :update, :destroy]
  # GET /paises
  # GET /paises.json
  def index
    @paises = Pais.all
  end

  # GET /paises/1
  # GET /paises/1.json
  def show
    @pais = Pais.find(params[:id])
  end

  # GET /paises/new
  # GET /paises/new.json
  def new
    @pais = Pais.new
  end

  # GET /paises/1/edit
  def edit
    @pais = Pais.find(params[:id])
  end

  # POST /paises
  # POST /paises.json
  def create
    @pais = Pais.new(pais_params)

    respond_to do |format|
      if @pais.save
        format.html { redirect_to @pais, notice: 'Um novo país foi criado com sucesso.' }
        format.json { render json: @pais, status: :created, location: @pais }
      else
        format.html { render action: "new" }
        format.json { render json: @pais.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /paises/1
  # PUT /paises/1.json
  def update
    respond_to do |format|
      if @pais.update_attributes(pais_params)
        format.html { redirect_to @pais, notice: 'O país foi atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pais.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paises/1
  # DELETE /paises/1.json
  def destroy
    @pais.destroy

    respond_to do |format|
      format.html { redirect_to paises_url }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_pais
      @pais = Pais.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pais_params
      params.require(:pais).permit(:nome)
    end
end

app/helpers/paises_helper.rb
module PaisesHelper
end

app/views/paises/_form.html.erb
<%= form_for(@pais) do |f| %>
  <% if @pais.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pais.errors.count, "error") %> Não foi possível salvar esse país:</h2>

      <ul>
      <% @pais.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paises/edit.html.erb
<h1>Editando um país</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @pais %> |
<%= link_to 'Voltar', paises_path %>

app/views/paises/index.html.erb
<h1>Listando países</h1>

<table>
  <tr>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @paises.each do |pais| %>
  <tr>
    <td><%= pais.nome %></td>
    <td><%= link_to 'Mostrar', pais %></td>
    <td><%= link_to 'Editar', edit_pais_path(pais) %></td>
    <td><%= link_to 'Apagar', pais, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Criar novo Pais', new_pais_path %>

app/views/paises/new.html.erb
<h1>Criar novo país</h1>

<%= render 'form' %>

<%= link_to 'Voltar', paises_path %>

app/views/paises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @pais.nome %>
</p>


<%= link_to 'Editar', edit_pais_path(@pais) %> |
<%= link_to 'Voltar', paises_path %>