config/routes.rb
CadastroDeFilmes::Application.routes.draw do
  resources :filmes

  resources :roteiristas

  resources :atores

  resources :midias

  resources :paises

  resources :generos

  resources :diretores

  root :to => 'filmes#index'

end

app/models/roteirista.rb
class Roteirista < ActiveRecord::Base
  has_and_belongs_to_many :filmes, :join_table => "roteiristas_filmes"

  validates :nome, uniqueness: true, presence: true
end

app/controllers/roteiristas_controller.rb
class RoteiristasController < ApplicationController
  before_action :set_roteirista, only: [:show, :edit, :update, :destroy]
  # GET /roteiristas
  # GET /roteiristas.json
  def index
    @search = Roteirista.search(params[:q])
    @roteiristas = @search.result
      .paginate(page: params[:page], per_page: 100)
  end

  # GET /roteiristas/1
  # GET /roteiristas/1.json
  def show
    @roteirista = Roteirista.find(params[:id])
  end

  # GET /roteiristas/new
  # GET /roteiristas/new.json
  def new
    @roteirista = Roteirista.new
  end

  # GET /roteiristas/1/edit
  def edit
    @roteirista = Roteirista.find(params[:id])
  end

  # POST /roteiristas
  # POST /roteiristas.json
  def create
    @roteirista = Roteirista.new(roteirista_params)

    respond_to do |format|
      if @roteirista.save
        format.html { redirect_to @roteirista, notice: 'Um novo roteirista foi criado.' }
        format.json { render json: @roteirista, status: :created, location: @roteirista }
      else
        format.html { render action: "new" }
        format.json { render json: @roteirista.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roteiristas/1
  # PUT /roteiristas/1.json
  def update
    respond_to do |format|
      if @roteirista.update_attributes(roteirista_params)
        format.html { redirect_to @roteirista, notice: 'O roteirista foi atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @roteirista.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roteiristas/1
  # DELETE /roteiristas/1.json
  def destroy
    @roteirista.destroy

    respond_to do |format|
      format.html { redirect_to roteiristas_url }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_roteirista
      @roteirista = Roteirista.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roteirista_params
      params.require(:roteirista).permit(:nome)
    end
end

app/helpers/roteiristas_helper.rb
module RoteiristasHelper
end

app/views/roteiristas/_form.html.erb
<%= form_for(@roteirista) do |f| %>
  <% if @roteirista.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@roteirista.errors.count, "error") %> Não foi possível salvar este roteirista:</h2>

      <ul>
      <% @roteirista.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roteiristas/edit.html.erb
<h1>Editando roteiristas</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @roteirista %> |
<%= link_to 'Voltar', roteiristas_path %>

app/views/roteiristas/index.html.erb
<h1>Listando roteiristas</h1>

<div id="search-form"> <fieldset>
  <legend>Buscar por nomes:</legend>
  <%= search_form_for @search do |f| %>
    <div class="field">
      <%= f.label :nome, "Nome: " %><br />
      <%= f.text_field :nome_cont, :class => "search-field"%>
    </div>
	<div class="actions">
	  <%= f.submit "Buscar" %>
    <%= f.submit "Limpar campos",  :id => :reset_btn  %>
	</div>
  <% end %>
</fieldset> </div>

<%= page_entries_info @roteiristas %>
<table>
  <tr>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @roteiristas.each do |roteirista| %>
  <tr>
    <td><%= roteirista.nome %></td>
    <td><%= link_to 'Mostrar', roteirista %></td>
    <td><%= link_to 'Editar', edit_roteirista_path(roteirista) %></td>
    <td><%= link_to 'Apagar', roteirista, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
  </tr>
<% end %>
</table>
<%= will_paginate @roteiristas %>

<br />

<%= link_to 'Criar novo Roteirista', new_roteirista_path %>

app/views/roteiristas/new.html.erb
<h1>Criar novo roteirista</h1>

<%= render 'form' %>

<%= link_to 'Voltar', roteiristas_path %>

app/views/roteiristas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @roteirista.nome %>
</p>


<%= link_to 'Editar', edit_roteirista_path(@roteirista) %> |
<%= link_to 'Voltar', roteiristas_path %>