config/routes.rb
CadastroDeFilmes::Application.routes.draw do
  resources :filmes

  resources :roteiristas

  resources :atores

  resources :midias

  resources :paises

  resources :generos

  resources :diretores

  root :to => 'filmes#index'

end

app/views/layouts/_footer.html.erb
<div id="footer">
  <p> </p>
  <p> Desenvolvido por <br>
  Luis Alexandre D. Brandão </p>
  <p> Techmago@ymail.com </p>
</div>

app/views/layouts/_header.html.erb
<div id="header">
  <p><h1> Catalogo de filmes assistidos </h1></p>
</div>

app/views/layouts/_links.html.erb
<li> <%= link_to 'Filmes', filmes_path %> </li>
<li> ---------------- </li>
<li> <%= link_to 'Atores', atores_path %> </li>
<li> <%= link_to 'Roteiristas', roteiristas_path %> </li>
<li> <%= link_to 'Diretores', diretores_path %> </li>
<li> <%= link_to 'Generos', generos_path %> </li>
<li> <%= link_to 'Midias', midias_path %> </li>
<li> <%= link_to 'Países', paises_path %> </li>

app/views/layouts/_sidebar.html.erb
<div id="sidebar">
  <ul id="sidebar-items">
    <li>
      <h3>Menu:</h3>
      <ul class="links">
        <%= render :partial => 'layouts/links' %>
      </ul>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <title> Cadastros De Filmes </title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
<div id="page">
  <%= render :partial => 'layouts/header' %>
  <%= render :partial => 'layouts/sidebar' %>
  <div id="content">
    <%= yield %>
  </div>
  <%= render :partial => 'layouts/footer' %>
</div>
</body>
</html>